id: autobugtracer.daily-run
namespace: autobugtracer
description: Daily AI-powered bug tracker & patch recommender

tasks:
  - id: trigger
    type: "io.kestra.plugin.core.trigger.Schedule"
    cron: "0 2 * * *"  # 2 AM Daily

  - id: fetch-git-commits
    type: io.kestra.plugin.git.Clone
    url: "https://github.com/your-org/your-repo"
    branch: main

  - id: fetch-issues
    type: "io.kestra.plugin.singer.taps.GitHub"
    accessToken: "{{ secrets.GITHUB_TOKEN }}"
    repositories: repo

  - id: fetch-logs
    type: io.kestra.plugin.aws.s3.List
    bucket: "your-log-bucket"
    prefix: "logs/{{ now | date('yyyy-MM-dd') }}/errors/"
    accessKeyId: "{{ secrets.AWS_KEY }}"
    secretKeyId: "{{ secrets.AWS_SECRET }}"

  - id: analyze
    type: io.kestra.plugin.openai.ChatCompletion
    apiKey: "{{ secrets.OPENAI_API_KEY }}"
    model: gpt-4
    prompt: |
      Using the following:
      - Git commits from the last 24 hours
      - Open GitHub issues with the label 'bug'
      - Logs from production

      Try to:
      1. Match error logs to known bugs
      2. Trace which commit likely introduced the issue
      3. Suggest a hotfix if possible, based on similar previous commits

      OUTPUT format:
      ```
      - Issue: [Title/Link]
      - Suspected Commit: [hash] - [message]
      - Suggested Fix: [patch]
      ```
    inputs:
      commits: "{{ outputs.fetch-git-commits.stdout }}"
      issues: "{{ outputs.fetch-issues.issues }}"
      logs: "{{ outputs.fetch-logs.files | map(attribute='uri') | join('\n') }}"




  - id: create-report
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - |
        echo "{{ outputs.analyze.choices[0].message.content }}" > report.md

  - id: post-to-slack
    type: "io.kestra.plugin.singer.taps.Slack"
    apiToken: "{{ secrets.SLACK_TOKEN }}"
    channels: "#bug-tracker"
    text: |
      AutoBugTracer Report:
      {{ outputs.analyze.choices[0].message.content }}

  - id: create-pr
    type: io.kestra.plugin.github.pulls.Search
    token: "{{ secrets.GITHUB_TOKEN }}"
    owner: your-org
    repo: your-repo
    base: main
    head: hotfix/autogenerated
    title: "AutoBugTracer: Suggested Hotfix"
    body: |
      This PR was auto-generated from the AutoBugTracer flow.
      {{ outputs.analyze.choices[0].message.content }}

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 2 * * *"
